import ProjectDescription

let config = Config(
    compatibleXcodeVersions: ["13.2.1"],
    generationOptions: [
        .organizationName("FooBar"),
        .developmentRegion("en-us"),
        .lastXcodeUpgradeCheck("13.2.1"),
        .disableAutogeneratedSchemes
    ]
)
